var roommateTypeDescriptions = {
    "The Organizer": "The Organizer is the type who alphabetizes their spice rack and color-codes their closet. They're on a first-name basis with the Container Store employees and think a fun Friday night involves a label maker. Beware: their idea of 'messy' is leaving one coffee cup in the sink.",
    "The Social Butterfly": "The Social Butterfly treats the apartment like a reality TV show set, where every night is a new episode filled with drama, laughter, and unexpected guests. They don't believe in 'too much party' and think silence is just unexplored space for conversation.",
    "The Homebody": "The Homebody has likely nested in the living room with a personal blanket fort. They treat the house like a personal hobbit hole, perfect for hibernation and not seeing the sun for days. They believe 'going out' is just a myth created by extroverts.",
    "The Adventurer": "The Adventurer is a mythical creature you're not sure actually lives in the house. Evidence of their existence includes a mysterious collection of souvenirs from around the world and occasional sightings at odd hours. They live by the motto, 'Why sleep when you can explore?'",
    "The Night Owl": "The Night Owl thrives in the darkness, their creativity sparking when everyone else is asleep. The fridge light is their sun, and they consider 3 AM an excellent time to start philosophical debates or craft their next masterpiece.",
    "The Early Bird": "The Early Bird annoyingly chirps about their morning run and smoothie while you're still struggling with the concept of consciousness. They've accomplished more by 8 AM than most do in a day and are suspiciously chipper before coffee.",
    "The Chef": "The Chef sees the kitchen as their stage, experimenting with recipes from around the globe. They believe that every meal is an opportunity for a culinary adventure, often leaving a trail of dishes and satisfied taste buds in their wake.",
    "The Green Thumb": "The Green Thumb has transformed the space into an indoor jungle, believing that plants are roommates too. Their care extends to every leaf and stem, creating an oasis that purifies the air and their souls.",
    "The Zen Master": "The Zen Master seeks harmony and balance in the living environment, turning the space into a retreat for mindfulness and meditation. Their presence is calming, often found sipping tea or practicing yoga in the living room.",
    "The Tech Wizard": "The Tech Wizard's room is a cave of gadgets, wires, and blinking lights. They're the go-to for fixing Wi-Fi issues or setting up the home theater system, often while mumbling about the latest tech trends.",
    "The Bookworm": "The Bookworm's territory is a library of tales and knowledge, with stacks of books in every corner. Quiet and thoughtful, they're often lost in another world, only emerging for the occasional snack or discussion about their latest read."
};
